In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ecommerce_data.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df.rename(columns={'product_photos_qty':'photos_count'}, inplace= True)
df.rename(columns= {'different_between_approved_purchase' : 'time_different_hour'}, inplace = True)
df.rename(columns = {'delivery' : 'delivered_on_time'}, inplace = True)
df

,order_status,payment_type,review_score,price,photos_count,time_different_hour,delivered_on_time,delivered_hour,delivered_season,seller_count
0,0,1,0,3,1,1,0,2,0,3
1,0,1,0,1,1,1,0,3,0,3
2,0,1,0,1,1,1,0,3,0,3
3,0,1,0,2,1,1,0,4,1,3
4,0,1,0,3,1,1,0,2,1,3
...,...,...,...,...,...,...,...,...,...,...
113212,0,1,0,1,1,1,0,1,1,1
113213,0,1,1,1,1,1,0,3,1,1
113214,0,1,0,1,2,2,0,2,1,1
113215,0,4,0,2,1,2,0,2,0,1
113216,0,1,0,6,5,1,0,4,1,1

In [3]:
order_status = {
    0 : 'delivered',
    1 : 'canceled'
}

In [4]:
df['order_status'] = df.order_status.map(order_status)

In [5]:
df.payment_type.value_counts()

1    83546
2    22022
3     6023
4     1626
Name: payment_type, dtype: int64

In [6]:
payment_type = {
    1 : 'credit_cart',
    2 : 'coupon',
    3 : 'voucher',
    4 : 'debit cart'
}

In [7]:
df['payment_type'] = df.payment_type.map(payment_type)

In [8]:
review_score = {
    0 : 'satisfied',
    1 : 'not satisfied'
}

In [9]:
df['review_score'] = df.review_score.map(review_score)

In [10]:
price = {
    1 : '<50',
    2 : '50 - 100',
    3 : '100 - 250',
    4 : '250 - 500',
    5 : '500 - 1000',
    6 : '1000 - 2000',
    7 : '2000 - 3000',
    8 : '3000 - 4000',
    9 : '4000 - 5000',
    10 : '>5000'
}

In [11]:
df['price'] = df.price.map(price)

In [12]:
def photos_count(x):
    if x <= 5:
        return 1
    elif x > 5 and x <= 10:
        return 2
    elif x > 10 and x <= 15:
        return 3
    else:
        return 4

In [13]:
df['photos_count'] = df.photos_count.apply(photos_count)

In [14]:
photos_count = {
    1 : '<5',
    2 : '5 - 10',
    3 : '10 -15',
    4 : '>15'
}

In [15]:
df['photos_count'] = df.photos_count.map(photos_count)

In [16]:
time_different_hour = {
    1 : '<1',
    2 : '1 - 5',
    3 : '5 - 10',
    4 : '10 - 20',
    5 : '20 - 30',
    6 : '30 - 40',
    7 : '40 - 50',
    8 : '>50'
}

In [17]:
df['time_different_hour'] = df.time_different_hour.map(time_different_hour)

In [18]:
delivery_on_time = {
    0 : 'No',
    1 : 'Yes'
}

In [19]:
df['delivered_on_time'] = df.delivered_on_time.map(delivery_on_time)

In [20]:
delivered_hour = {
    1 : 'Morning',
    2 : 'Midday',
    3 : 'Evening',
    4 : 'Night'
}

In [21]:
df['delivered_hour'] = df.delivered_hour.map(delivered_hour)

In [22]:
df['delivered_season'] = df['delivered_season'].apply(lambda x: 'Winter' if x == 1 else 'Summer')

In [23]:
seller_count = {
    1 : '<10',
    2 : '10 - 50',
    3 : '50 - 250',
    4 : '250 - 500',
    5 : '500 - 1000',
    6 : '1000 - 2000',
    7 : '2000 - 3000',
    8 : '3000 - 4000',
    9 : '4000 - 5000',
    10 : '>5000'
}

In [24]:
df['seller_count'] = df.seller_count.map(seller_count)

In [25]:
df.head(60)

,order_status,payment_type,review_score,price,photos_count,time_different_hour,delivered_on_time,delivered_hour,delivered_season,seller_count
0,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
1,delivered,credit_cart,satisfied,<50,<5,<1,No,Evening,Summer,50 - 250
2,delivered,credit_cart,satisfied,<50,<5,<1,No,Evening,Summer,50 - 250
3,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Night,Winter,50 - 250
4,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Winter,50 - 250
5,delivered,debit cart,satisfied,100 - 250,<5,40 - 50,No,Night,Winter,50 - 250
6,delivered,coupon,satisfied,500 - 1000,<5,10 - 20,No,Night,Winter,50 - 250
7,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Morning,Summer,50 - 250
8,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Winter,50 - 250
9,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Winter,50 - 250
10,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Winter,50 - 250
11,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Winter,50 - 250
12,delivered,credit_cart,not satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
13,delivered,credit_cart,not satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
14,delivered,credit_cart,not satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
15,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Evening,Winter,50 - 250
16,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
17,delivered,coupon,satisfied,50 - 100,<5,10 - 20,No,Morning,Summer,50 - 250
18,delivered,credit_cart,not satisfied,100 - 250,<5,<1,Yes,Evening,Summer,50 - 250
19,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Winter,50 - 250
20,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Winter,50 - 250
21,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Night,Winter,50 - 250
22,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Evening,Summer,50 - 250
23,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
24,delivered,coupon,satisfied,100 - 250,<5,10 - 20,No,Midday,Summer,50 - 250
25,delivered,coupon,satisfied,100 - 250,<5,10 - 20,No,Midday,Summer,50 - 250
26,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Morning,Summer,50 - 250
27,delivered,credit_cart,satisfied,50 - 100,<5,1 - 5,No,Night,Summer,50 - 250
28,delivered,coupon,satisfied,100 - 250,<5,30 - 40,No,Night,Summer,50 - 250
29,delivered,credit_cart,satisfied,<50,<5,<1,No,Evening,Winter,50 - 250
30,delivered,coupon,satisfied,100 - 250,<5,>50,No,Evening,Winter,50 - 250
31,delivered,coupon,satisfied,100 - 250,<5,>50,No,Evening,Winter,50 - 250
32,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Summer,50 - 250
33,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
34,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
35,delivered,credit_cart,satisfied,100 - 250,<5,1 - 5,No,Midday,Winter,50 - 250
36,delivered,coupon,satisfied,100 - 250,<5,10 - 20,No,Evening,Summer,50 - 250
37,delivered,coupon,not satisfied,100 - 250,<5,40 - 50,No,Midday,Summer,50 - 250
38,delivered,coupon,not satisfied,100 - 250,<5,40 - 50,No,Midday,Summer,50 - 250
39,delivered,coupon,not satisfied,100 - 250,<5,40 - 50,No,Midday,Summer,50 - 250
40,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Morning,Winter,50 - 250
41,delivered,credit_cart,satisfied,100 - 250,<5,20 - 30,No,Evening,Winter,50 - 250
42,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
43,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
44,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Evening,Winter,50 - 250
45,delivered,coupon,satisfied,100 - 250,<5,10 - 20,No,Evening,Summer,50 - 250
46,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
47,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
48,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
49,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Evening,Summer,50 - 250
50,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Summer,50 - 250
51,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Midday,Summer,50 - 250
52,delivered,credit_cart,satisfied,50 - 100,<5,<1,No,Midday,Summer,50 - 250
53,delivered,coupon,satisfied,50 - 100,<5,10 - 20,No,Morning,Summer,50 - 250
54,delivered,coupon,satisfied,50 - 100,<5,10 - 20,No,Morning,Summer,50 - 250
55,delivered,coupon,satisfied,100 - 250,<5,>50,No,Midday,Winter,50 - 250
56,delivered,coupon,satisfied,250 - 500,<5,40 - 50,No,Midday,Winter,50 - 250
57,delivered,credit_cart,satisfied,50 - 100,<5,20 - 30,Yes,Midday,Winter,50 - 250
58,delivered,credit_cart,satisfied,50 - 100,<5,20 - 30,Yes,Midday,Winter,50 - 250
59,delivered,credit_cart,satisfied,100 - 250,<5,<1,No,Morning,Summer,50 - 250

In [27]:
df.to_csv('cleaned_data')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113217 entries, 0 to 113216
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_status         113217 non-null  object
 1   payment_type         113217 non-null  object
 2   review_score         113217 non-null  object
 3   price                113217 non-null  object
 4   photos_count         113217 non-null  object
 5   time_different_hour  113217 non-null  object
 6   delivered_on_time    113217 non-null  object
 7   delivered_hour       113217 non-null  object
 8   delivered_season     113217 non-null  object
 9   seller_count         113217 non-null  object
dtypes: object(10)
memory usage: 8.6+ MB

In [29]:
df.delivered_on_time.value_counts()

No     103140
Yes     10077
Name: delivered_on_time, dtype: int64